name: Merge Request

on:
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
      - uses: .github/actions/cache

      - name: Lint
        run: |
          npm run lint

      - name: Test
        run: |
          npm run test -- -c production

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/cobertura-coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Build
        run: |
          npm run build
